-- Create dedicated Nacionalidade table
CREATE TABLE IF NOT EXISTS nacionalidade (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) UNIQUE NOT NULL,
  flag VARCHAR(255),
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
