import * as fs from "fs";
import * as path from "path";
import { AppDataSource } from "../config/database";

function getDatabaseType(): "mysql" | "postgres" {
  const type = AppDataSource.options.type;
  return type === "postgres" ? "postgres" : "mysql";
}

const isPostgres = getDatabaseType() === "postgres";

const MIGRATIONS_TABLE = isPostgres
  ? `
CREATE TABLE IF NOT EXISTS schema_migrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename VARCHAR(255) UNIQUE NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)`
  : `
CREATE TABLE IF NOT EXISTS schema_migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) UNIQUE NOT NULL,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;

/**
 * Remove comentários de linha no início do statement.
 */
function normalizeStatement(sql: string): string {
  return sql
    .replace(/^(\s*--[^\n]*\n)+/m, "")
    .trim();
}

/**
 * Divide SQL em statements respeitando blocos DO $$ ... $$.
 */
function splitSqlStatements(sql: string): string[] {
  const statements: string[] = [];
  let current = "";
  let inDollarQuote = false;

  for (let i = 0; i < sql.length; i++) {
    if (sql[i] === "$" && sql[i + 1] === "$") {
      inDollarQuote = !inDollarQuote;
      current += "$$";
      i++;
      continue;
    }

    if (sql[i] === ";" && !inDollarQuote) {
      const trimmed = normalizeStatement(current);
      if (trimmed.length > 0) {
        statements.push(trimmed);
      }
      current = "";
      continue;
    }

    current += sql[i];
  }

  const tail = normalizeStatement(current);
  if (tail.length > 0) {
    statements.push(tail);
  }

  return statements;
}

async function hasTable(tableName: string): Promise<boolean> {
  const isPostgresDb = getDatabaseType() === "postgres";
  const placeholder = isPostgresDb ? "$1" : "?";
  const schemaCondition = isPostgresDb ? "current_schema()" : "DATABASE()";
  const rows: Array<{ count: number }> = await AppDataSource.query(
    `SELECT COUNT(*) AS count FROM information_schema.tables WHERE table_schema = ${schemaCondition} AND table_name = ${placeholder}`,
    [tableName]
  );
  return rows[0]?.count > 0;
}

async function ensureBaseSchema(): Promise<void> {
  const hasUserTable = await hasTable("user");
  const hasLivroTable = await hasTable("livro");

  if (!hasUserTable || !hasLivroTable) {
    console.log("▶ Tabelas base ausentes; criando schema inicial via TypeORM...");
    await AppDataSource.synchronize();
    console.log("✓ Schema inicial criado via TypeORM");
  }
}

function isIgnorableMigrationError(err: unknown): boolean {
  if (!err || typeof err !== "object") return false;

  const castErr = err as { code?: string; errno?: number };
  const duplicateIndex = castErr.code === "ER_DUP_KEYNAME" || castErr.errno === 1061;
  const duplicateForeignKey = castErr.code === "ER_FK_DUP_NAME" || castErr.errno === 1826;
  const duplicateColumn = castErr.code === "ER_DUP_FIELDNAME" || castErr.errno === 1060;
  return duplicateIndex || duplicateForeignKey || duplicateColumn;
}

async function getAppliedMigrations(): Promise<Set<string>> {
  const rows: Array<{ filename: string }> = await AppDataSource.query(
    `SELECT filename FROM schema_migrations ORDER BY id`
  );
  return new Set(rows.map((r) => r.filename));
}

export async function runMigrations(): Promise<void> {
  await AppDataSource.query(MIGRATIONS_TABLE);
  await ensureBaseSchema();

  if (isPostgres) {
    console.log("▶ PostgreSQL detectado; pulando migrations SQL manuais e usando o schema do TypeORM.");
    return;
  }

  try {
    const migrationsDir = path.join(__dirname, "../../migrations");
    if (!fs.existsSync(migrationsDir)) {
      console.warn("Pasta migrations/ não encontrada — nenhuma migration aplicada.");
      return;
    }

    const files = fs
      .readdirSync(migrationsDir)
      .filter((f) => f.endsWith(".sql"))
      .sort();

    const applied = await getAppliedMigrations();

    for (const file of files) {
      if (applied.has(file)) continue;

      const fullPath = path.join(migrationsDir, file);
      const sql = fs.readFileSync(fullPath, "utf8");
      const statements = splitSqlStatements(sql);

      console.log(`▶ Aplicando migration: ${file} (${statements.length} statements)`);

      const queryRunner = AppDataSource.createQueryRunner();
      await queryRunner.connect();

      try {
        for (const statement of statements) {
          try {
            await queryRunner.query(statement);
          } catch (error: unknown) {
            if (isIgnorableMigrationError(error)) {
              console.warn(`! Statement ignorado em ${file}:`, (error as any).sqlMessage || (error as any).message || error);
              continue;
            }
            throw error;
          }
        }
        await queryRunner.query(`INSERT INTO schema_migrations (filename) VALUES (?)`, [file]);
        console.log(`✓ Migration aplicada: ${file}`);
      } finally {
        await queryRunner.release();
      }
    }
  } catch (err) {
    console.error("✗ Erro ao executar migrations:", err);
    throw err;
  }
}
